// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lamzrzfjptmxqinfiwxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhbXpyemZqcHRteHFpbmZpd3h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxNjA5NzQsImV4cCI6MjA4NzczNjk3NH0.ztu4LpH_xZhWRWaT4PE44-Iy8cdgJocyf9WYEW3bS1I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});